name: shuvautsavapp
description: "A new Flutter project."

publish_to: "none"

version: 0.0.26+26
environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.4
  riverpod: ^2.5.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  json_serializable: ^6.8.0
  hugeicons: ^0.0.7
  dio: ^5.7.0
  chucker_flutter: ^1.8.1
  connectivity_plus: ^6.1.0
  fluttertoast: ^8.2.8
  flutter_widget_from_html: ^0.15.2
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  intl: any
  path_provider: ^2.0.10
  path: ^1.8.0
  smooth_page_indicator: ^1.2.0+3
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.5.1
  flutter_secure_storage: ^4.2.1
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
  # webview_flutter: ^4.10.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^6.0.4
  firebase_core: ^3.8.1
  flutter_rating_bar: ^4.0.1
  sign_in_with_apple: ^6.1.4
  flutter_inappwebview: ^6.1.5
  collection: ^1.19.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.1"
  build_runner: ^2.4.11
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_launcher_icon.png"
